//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSSceneReader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousOpen {
            get {
                return ((string)(this["PreviousOpen"]));
            }
            set {
                this["PreviousOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point previewPosition {
            get {
                return ((global::System.Drawing.Point)(this["previewPosition"]));
            }
            set {
                this["previewPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size previewSize {
            get {
                return ((global::System.Drawing.Size)(this["previewSize"]));
            }
            set {
                this["previewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool previewSave {
            get {
                return ((bool)(this["previewSave"]));
            }
            set {
                this["previewSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte skyDrawMode {
            get {
                return ((byte)(this["skyDrawMode"]));
            }
            set {
                this["skyDrawMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte worldDrawMode {
            get {
                return ((byte)(this["worldDrawMode"]));
            }
            set {
                this["worldDrawMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte objectDrawMode {
            get {
                return ((byte)(this["objectDrawMode"]));
            }
            set {
                this["objectDrawMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color railColor {
            get {
                return ((global::System.Drawing.Color)(this["railColor"]));
            }
            set {
                this["railColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color railSelColor {
            get {
                return ((global::System.Drawing.Color)(this["railSelColor"]));
            }
            set {
                this["railSelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YellowGreen")]
        public global::System.Drawing.Color railNodeColor {
            get {
                return ((global::System.Drawing.Color)(this["railNodeColor"]));
            }
            set {
                this["railNodeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color railNodeSelColor {
            get {
                return ((global::System.Drawing.Color)(this["railNodeSelColor"]));
            }
            set {
                this["railNodeSelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color objColor {
            get {
                return ((global::System.Drawing.Color)(this["objColor"]));
            }
            set {
                this["objColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color objSelColor {
            get {
                return ((global::System.Drawing.Color)(this["objSelColor"]));
            }
            set {
                this["objSelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cameraMoveY {
            get {
                return ((bool)(this["cameraMoveY"]));
            }
            set {
                this["cameraMoveY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 32")]
        public global::System.Drawing.Color voidColor {
            get {
                return ((global::System.Drawing.Color)(this["voidColor"]));
            }
            set {
                this["voidColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool needsUpgrade {
            get {
                return ((bool)(this["needsUpgrade"]));
            }
            set {
                this["needsUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500000")]
        public float previewDrawDistance {
            get {
                return ((float)(this["previewDrawDistance"]));
            }
            set {
                this["previewDrawDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState previewState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["previewState"]));
            }
            set {
                this["previewState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainPreviewLoad {
            get {
                return ((bool)(this["mainPreviewLoad"]));
            }
            set {
                this["mainPreviewLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainLoadSeconds {
            get {
                return ((bool)(this["mainLoadSeconds"]));
            }
            set {
                this["mainLoadSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainShortcuts {
            get {
                return ((bool)(this["mainShortcuts"]));
            }
            set {
                this["mainShortcuts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool previewOrigin {
            get {
                return ((bool)(this["previewOrigin"]));
            }
            set {
                this["previewOrigin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string commonPath {
            get {
                return ((string)(this["commonPath"]));
            }
            set {
                this["commonPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string stageArc {
            get {
                return ((string)(this["stageArc"]));
            }
            set {
                this["stageArc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float cameraSpeed {
            get {
                return ((float)(this["cameraSpeed"]));
            }
            set {
                this["cameraSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string paramPath {
            get {
                return ((string)(this["paramPath"]));
            }
            set {
                this["paramPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool showParamInfo {
            get {
                return ((bool)(this["showParamInfo"]));
            }
            set {
                this["showParamInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool paramHex {
            get {
                return ((bool)(this["paramHex"]));
            }
            set {
                this["paramHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string previewSizeX {
            get {
                return ((string)(this["previewSizeX"]));
            }
            set {
                this["previewSizeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string previewSizeY {
            get {
                return ((string)(this["previewSizeY"]));
            }
            set {
                this["previewSizeY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad1")]
        public global::System.Windows.Forms.Keys KeyBindFrontView {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindFrontView"]));
            }
            set {
                this["KeyBindFrontView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad3")]
        public global::System.Windows.Forms.Keys KeyBindRightView {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindRightView"]));
            }
            set {
                this["KeyBindRightView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad5")]
        public global::System.Windows.Forms.Keys KeyBindOrthoView {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindOrthoView"]));
            }
            set {
                this["KeyBindOrthoView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NumPad7")]
        public global::System.Windows.Forms.Keys KeyBindTopView {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindTopView"]));
            }
            set {
                this["KeyBindTopView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.Windows.Forms.Keys KeyBindMoveForward {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindMoveForward"]));
            }
            set {
                this["KeyBindMoveForward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys KeyBindMoveBackward {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindMoveBackward"]));
            }
            set {
                this["KeyBindMoveBackward"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys KeyBindMoveLeft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindMoveLeft"]));
            }
            set {
                this["KeyBindMoveLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys KeyBindMoveRight {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindMoveRight"]));
            }
            set {
                this["KeyBindMoveRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::System.Windows.Forms.Keys KeyBindMoveUp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindMoveUp"]));
            }
            set {
                this["KeyBindMoveUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q")]
        public global::System.Windows.Forms.Keys KeyBindMoveDown {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindMoveDown"]));
            }
            set {
                this["KeyBindMoveDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public global::System.Windows.Forms.Keys KeyBindStartDrag {
            get {
                return ((global::System.Windows.Forms.Keys)(this["KeyBindStartDrag"]));
            }
            set {
                this["KeyBindStartDrag"] = value;
            }
        }

                [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SimplerRendering {
            get {
                return ((bool)(this["SimplerRendering"]));
            }
            set {
                this["SimplerRendering"] = value;
            }
        }

    }
}
